[package]
name = "misskey-booru-rs"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
codegen-units = 1
panic = "abort"
lto = "fat"
strip = "symbols"

[dependencies]
nanoserde = "0.2.1"
rand = "0.9.1"
ureq = { version = "3.0.11", features = ["json"] }
