[account]
token = "asdasdasd" # must have read:drive, write:drive, write:notes
instance_url = "https://miruku.cafe" # no trailing slash!

[post]
message = """Look it's Megumin!
#megumin"""
append_post_url = true
visibility = "followers" # | public | home
sensitive = false # | true

[gelbooru]
booru_url = "https://gelbooru.com" # no trailing slash!
tags = ["megumin", "rating:general"]
divisor = 1 # whole number. if there are 1000 posts and the divisor is 4, only the first 250 posts will be picked

[bot]
post_interval = 3600 # seconds
error_timeout = 30
